name: Create release

on:
  push:
    branches:
      - main
      - resource-catalog

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.rp.outputs.release_created }}
      tag_name: ${{ steps.rp.outputs.tag_name }}
      upload_url: ${{ steps.rp.outputs.upload_url }}
    steps:
      - name: Release please
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

  build-publish:
    name: Build and publish module
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Build legacy bundle
        run: npx esbuild ./dist/access-ci-ui.js --bundle --minify --outfile=./dist/access-ci-ui.bundle.js --global-name=AccessCiUi
      - name: Determine NPM tag
        id: npm-tag
        run: echo npm-tag=$(jq -r .version package.json | grep -q 'alpha\|beta\|rc' && echo "next" || echo "latest") >> $GITHUB_OUTPUT
      - run: npm publish --provenance --access public --tag ${{ steps.npm-tag.outputs.npm-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
